create_clock -name fpga_clk -period 10 [get_ports fpga_clk]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P17 } [get_ports fpga_clk ]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P15 } [get_ports fpga_rstn]

# 拨码开关 (switch[15:8]对应8个拨码开关, switch[7:0]对应8位数码开关; 高位在左, 低位在右)
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P5 } [get_ports switch[15]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P4 } [get_ports switch[14]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P3 } [get_ports switch[13]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P2 } [get_ports switch[12]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN R2 } [get_ports switch[11]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN M4 } [get_ports switch[10]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN N4 } [get_ports switch[ 9]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN R1 } [get_ports switch[ 8]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN U3 } [get_ports switch[ 7]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN U2 } [get_ports switch[ 6]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN V2 } [get_ports switch[ 5]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN V5 } [get_ports switch[ 4]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN V4 } [get_ports switch[ 3]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN R3 } [get_ports switch[ 2]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN T3 } [get_ports switch[ 1]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN T5 } [get_ports switch[ 0]]

# 按键开关 button[4:0] == {S4, S3, S2, S1, S0}
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN U4 } [get_ports button[4]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN V1 } [get_ports button[3]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN R15} [get_ports button[2]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN R17} [get_ports button[1]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN R11} [get_ports button[0]]

# 数码管
# 高4位段选信号 led_seg0[7:0] == LED0_{CA, CB, ..., DP}
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN B4 } [get_ports led_seg0[7]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN A4 } [get_ports led_seg0[6]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN A3 } [get_ports led_seg0[5]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN B1 } [get_ports led_seg0[4]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN A1 } [get_ports led_seg0[3]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN B3 } [get_ports led_seg0[2]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN B2 } [get_ports led_seg0[1]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN D5 } [get_ports led_seg0[0]]
# 低4位段选信号 led_seg1[7:0] == LED1_{CA, CB, ..., DP}
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN D4 } [get_ports led_seg1[7]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN E3 } [get_ports led_seg1[6]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN D3 } [get_ports led_seg1[5]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F4 } [get_ports led_seg1[4]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F3 } [get_ports led_seg1[3]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN E2 } [get_ports led_seg1[2]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN D2 } [get_ports led_seg1[1]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN H2 } [get_ports led_seg1[0]]
# 位选信号 (高位在左, 低位在右)
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN G2 } [get_ports led_en[7]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN C2 } [get_ports led_en[6]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN C1 } [get_ports led_en[5]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN H1 } [get_ports led_en[4]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN G1 } [get_ports led_en[3]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F1 } [get_ports led_en[2]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN E1 } [get_ports led_en[1]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN G6 } [get_ports led_en[0]]

# LED (高位在左, 低位在右)
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F6 } [get_ports led[15]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN G4 } [get_ports led[14]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN G3 } [get_ports led[13]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN J4 } [get_ports led[12]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN H4 } [get_ports led[11]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN J3 } [get_ports led[10]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN J2 } [get_ports led[ 9]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K2 } [get_ports led[ 8]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K1 } [get_ports led[ 7]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN H6 } [get_ports led[ 6]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN H5 } [get_ports led[ 5]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN J5 } [get_ports led[ 4]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K6 } [get_ports led[ 3]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN L1 } [get_ports led[ 2]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN M1 } [get_ports led[ 1]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K3 } [get_ports led[ 0]]
